#ifndef UBIQUITOUS_OCTO_CARNIVAL_HTTP__HTTP_SERVER_H_
#define UBIQUITOUS_OCTO_CARNIVAL_HTTP__HTTP_SERVER_H_


#define MAX_GET_REQUEST_LENGTH (10 * 1024) // 10KB

#endif //UBIQUITOUS_OCTO_CARNIVAL_HTTP__HTTP_SERVER_H_
