#ifndef UBIQUITOUS_OCTO_CARNIVAL_HTTP__HTTP_SERVER_H_
#define UBIQUITOUS_OCTO_CARNIVAL_HTTP__HTTP_SERVER_H_


#define MAX_GET_REQUEST_LENGTH (10 * 1024) // 10KB
#define MAX_FILE_NAME 1024
#define MAX_FILE_NAME_EXTENSION 32

#endif //UBIQUITOUS_OCTO_CARNIVAL_HTTP__HTTP_SERVER_H_
